name: tercen_ui_orchestrator
description: Tercen AI-driven UI orchestrator.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.5
  sdui:
    path: ../sdui
  sci_tercen_client:
    git:
      ref: 1.16.1
      url: https://github.com/tercen/sci_tercen_client
      path: sci_tercen_client
  sci_base:
    git:
      ref: 1.16.1
      url: https://github.com/tercen/sci_tercen_client
      path: sci_base
  sci_http_client:
    git:
      ref: 1.16.1
      url: https://github.com/tercen/sci_tercen_client
      path: sci_http_client
  sci_tercen_context:
    git:
      ref: 1.16.1
      url: https://github.com/tercen/sci_tercen_client
      path: sci_tercen_context

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
