name: tercen_orchestrator_server
description: Backend server for Tercen UI Orchestrator
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
